{
  "name": "mood-diary-api",
  "compatibility_date": "2026-02-10",
  "main": "workers/api.js",
  "d1_databases": [
    {
      "binding": "DB",
      "database_name": "mood-diary-db",
      "database_id": "eb51fc89-c25d-4887-8cb3-e349c22bc18a"
    }
  ]
}
